project_id = "rczkairulwcwtbjlkyge"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://rczkairulwcwtbjlkyge.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"
image_transformation = true

[functions.mp-oauth-authorize]
verify_jwt = true

[functions.mp-oauth-callback]
verify_jwt = false

[functions.mp-create-preference]
verify_jwt = true

[functions.mp-create-appointment-preference]
verify_jwt = true

[functions.mp-webhooks]
verify_jwt = false

[db]
major_version = 15

[studio]
enabled = true
port = 54324

[[local_storage.buckets]]
name = "product-images"
public = true