// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rczkairulwcwtbjlkyge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjemthaXJ1bHdjd3RiamxreWdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzE0NDksImV4cCI6MjA2ODYwNzQ0OX0.LxGg53_87kaWt_nx0sfVV0Kz0jxrfPDX071wCnCK5H4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});